FIX: case-sensitivity, using 'PcmPy' instead of 'PCMPy'
Current documentation returns:

    import PCMPy as pcm
ModuleNotFoundError: No module named 'PCMPy'